language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-14

script:
  - export CC=gcc-14
  - export CXX=g++-14
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target neat
